### ISSUE TITLE
any schedule to upgrade to RN 0.62.x ?

### ISSUE THREAD

**Issue by jfroffice** [karanpratapsingh/react-native-boilerplate#11]
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

**Comment by karanpratapsingh** [comment]
Thanks for mention, I’ll try to do this week for sure

**Comment by karanpratapsingh** [comment]
@jfroffice Hey, I've updated it to RN 0.62.2, please do a pull of master and enjoy 😄
