### ISSUE TITLE
Need permission to copy your readme file

### ISSUE THREAD

**Issue by alexakasanjeev** [karanpratapsingh/react-native-boilerplate#5]
Hi Karan,

I read your readme file for this repo, and it is very well organized. I have similar repo [`react-native-boilerplate`](https://github.com/alexakasanjeev/react-native-boilerplate), and I would like to copy the readme file to my own repo.

I hope that's ok.

PS: Couldn't find your mail id, that's why created this issue, feel free to close the issue.

**Comment by karanpratapsingh** [comment]
Yes, sure you can take some stuff, don't think of it as copying. it's opensource brother 😄

**Comment by alexakasanjeev** [comment]
Thank you
