### ISSUE TITLE
Intregate Storybook

### ISSUE THREAD

**Issue by alexakasanjeev** [karanpratapsingh/react-native-boilerplate#6]
Hi Karan,

Your boilerplate code is well organized. I use [storybook](https://storybook.js.org/) to develop my components in isolation. It would be great if storybook integration is added into boilerplate. And the best part of `storybook` is, it won't hinder your development flow, can be easily removed and switching between storybook mode and actual app content is easy.

If you want, I would like to create pull request containing storybook integration to this repo.

**Comment by karanpratapsingh** [comment]
Thank you for your kind comment. Yes storybook is amazing, but to be honest, I'm currently trying to keep this boilerplate minimum and less opinionated.

for example I added typescript integration as optional and can be used via the `typescript.sh`, if you can do something similar for storybook that would be great. I think it's important to let people choose 😄
