### ISSUE TITLE
Failing at yarn ios

### ISSUE THREAD

**Issue by vasujogani** [karanpratapsingh/react-native-boilerplate#8]
![image](https://user-images.githubusercontent.com/18491558/71143118-0eec1d00-21df-11ea-8662-45165f75832e.png)

**Comment by karanpratapsingh** [comment]
Thank you for reporting, I noticed this yesterday too, I'm publishing a fix very soon 😄 , basically, you have to remove assets from your build phases in xcode, I'll push the update in few hrs

**Comment by karanpratapsingh** [comment]
I've done a hotfix on the master branch, basically, these resources were being duplicated

<img width="708" alt="Screenshot 2019-12-19 at 3 38 02 PM" src="https://user-images.githubusercontent.com/29705703/71165562-0f37f700-2277-11ea-92d2-dc6d708c2e2b.png">
